version: '3.5'
services:
  meraki-mqtt:
    image: eclipse-mosquitto:latest
    container_name: meraki-mqtt
    volumes: 
      - ./mqtt:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - proxynet

networks:
  proxynet:
    external:
      name: proxy_sites
